<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '26163c880a9b24788c4f1b901712c9a1',
  'CORS_ALLOW_ORIGIN' => '^http?://localhost(:[0-9]+)?$',
  'DATABASE_URL' => 'mysql://da:da@localhost:3306/libre?serverVersion=mariadb-10.5.4',
);
